import { existsSync, mkdirSync, writeFileSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import matter from 'gray-matter';

export interface TaskFrontmatter {
  id: string;
  title: string;
  status: 'backlog' | 'ready' | 'in-progress' | 'review' | 'deploying' | 'monitoring' | 'done';
  project: string;
  priority: 'critical' | 'high' | 'medium' | 'low';
  created: string;
  provider?: string;
  review_model?: string;
  tags: string[];
  complexity: 'low' | 'medium' | 'high';
  branch: string;
  deploy_env?: string;
}

const VAULT_DIRS = [
  '_oasis/templates',
  'projects',
  'wiki/concepts',
  'wiki/patterns',
  'wiki/entities',
  'wiki/summaries',
  'raw-sources',
];

const SCHEMA_TEMPLATE = `# Oasis Vault Schema

This vault is managed by Oasis — a provider-agnostic AI dev orchestrator.

## Structure

- \`projects/\` — One folder per project, each with backlog/, decisions/, skills/
- \`wiki/\` — Auto-maintained knowledge base (LLM Wiki pattern)
- \`raw-sources/\` — Articles, transcripts, images for ingestion
- \`_oasis/\` — Internal system files (templates, index)

## Task Status Flow

\`backlog → ready → in-progress → review → deploying → done\`

## Operations

- **Ingest**: Add raw sources → AI processes and updates wiki
- **Query**: Ask questions against the wiki
- **Lint**: Health check for contradictions, orphans, stale content
`;

const TASK_TEMPLATE = `---
id: "{{ID}}"
title: "{{TITLE}}"
status: backlog
project: "{{PROJECT}}"
priority: medium
created: "{{DATE}}"
tags: []
complexity: low
branch: ""
---

## Description


## Acceptance Criteria
- [ ]

## Context Notes

## SDD Artifacts

## Review Notes

## Deploy Log
`;

const INDEX_TEMPLATE = `# Vault Index

Auto-maintained by Oasis. Do not edit manually.

## Projects

## Wiki Pages

## Recent Activity
`;

export function createVaultStructure(vaultPath: string): void {
  for (const dir of VAULT_DIRS) {
    const fullPath = join(vaultPath, dir);
    if (!existsSync(fullPath)) {
      mkdirSync(fullPath, { recursive: true });
    }
  }

  // Write schema
  const schemaPath = join(vaultPath, '_oasis/schema.md');
  if (!existsSync(schemaPath)) {
    writeFileSync(schemaPath, SCHEMA_TEMPLATE, 'utf-8');
  }

  // Write task template
  const taskTemplatePath = join(vaultPath, '_oasis/templates/task.md');
  if (!existsSync(taskTemplatePath)) {
    writeFileSync(taskTemplatePath, TASK_TEMPLATE, 'utf-8');
  }

  // Write index
  const indexPath = join(vaultPath, '_oasis/index.md');
  if (!existsSync(indexPath)) {
    writeFileSync(indexPath, INDEX_TEMPLATE, 'utf-8');
  }

  // Write log
  const logPath = join(vaultPath, 'log.md');
  if (!existsSync(logPath)) {
    writeFileSync(logPath, `# Oasis Log\n\nChronological record of all operations.\n\n`, 'utf-8');
  }

  // Write action tracker
  const actionPath = join(vaultPath, 'Action-Tracker.md');
  if (!existsSync(actionPath)) {
    writeFileSync(actionPath, `# Action Tracker\n\nPending actions across all projects.\n\n`, 'utf-8');
  }
}

export function registerProject(vaultPath: string, projectName: string): void {
  const projectDir = join(vaultPath, 'projects', projectName);
  const dirs = ['backlog', 'decisions', 'skills'];

  for (const dir of dirs) {
    const fullPath = join(projectDir, dir);
    if (!existsSync(fullPath)) {
      mkdirSync(fullPath, { recursive: true });
    }
  }

  // Create default project.yaml if it doesn't exist
  const projectYamlPath = join(projectDir, 'project.yaml');
  if (!existsSync(projectYamlPath)) {
    const defaultConfig = `# Project: ${projectName}
# Generated by Oasis

review:
  provider: ""  # uses default provider
  model: ""     # uses default model
  phases:
    proposal: auto
    spec: auto
    design: human
    tasks: auto
    apply: auto
    verify: auto
  max_retries: 2

scheduler:
  auto_start: false
  notify: both

deploy:
  environments: {}

observability:
  health_endpoints: []
  log_command: ""
  rollback_command: ""
  monitor_interval_seconds: 60
  max_failures_before_rollback: 3
`;
    writeFileSync(projectYamlPath, defaultConfig, 'utf-8');
  }
}

export function listProjects(vaultPath: string): string[] {
  const projectsDir = join(vaultPath, 'projects');
  if (!existsSync(projectsDir)) return [];
  return readdirSync(projectsDir, { withFileTypes: true })
    .filter(d => d.isDirectory())
    .map(d => d.name);
}

export function listTasks(vaultPath: string, projectName: string, statusFilter?: string): TaskFrontmatter[] {
  const backlogDir = join(vaultPath, 'projects', projectName, 'backlog');
  if (!existsSync(backlogDir)) return [];

  const files = readdirSync(backlogDir).filter(f => f.endsWith('.md'));
  const tasks: TaskFrontmatter[] = [];

  for (const file of files) {
    try {
      const content = readFileSync(join(backlogDir, file), 'utf-8');
      const { data } = matter(content);
      const task = data as TaskFrontmatter;
      if (!statusFilter || task.status === statusFilter) {
        tasks.push(task);
      }
    } catch {
      // Skip malformed files
    }
  }

  return tasks;
}

export function getNextReadyTask(vaultPath: string, projectName: string): TaskFrontmatter | null {
  const tasks = listTasks(vaultPath, projectName, 'ready');
  if (tasks.length === 0) return null;

  const priorityOrder: Record<string, number> = {
    critical: 0,
    high: 1,
    medium: 2,
    low: 3,
  };

  tasks.sort((a, b) => (priorityOrder[a.priority] ?? 9) - (priorityOrder[b.priority] ?? 9));
  return tasks[0];
}

export function hasInProgressTask(vaultPath: string, projectName: string): boolean {
  return listTasks(vaultPath, projectName, 'in-progress').length > 0;
}
